# Generated by Django 4.1.1 on 2022-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo Electronico')),
                ('motivo', models.CharField(choices=[('IG', 'InformacionGeneral'), ('P', 'Pedidos'), ('C', 'Comentarios'), ('PQR', 'PQRs')], default='C', max_length=4, verbose_name='Motivo de Contacto')),
                ('comentario', models.CharField(max_length=300, verbose_name='Comentarios')),
                ('respuesta', models.BooleanField()),
            ],
        ),
    ]
