# Generated by Django 4.1.1 on 2022-12-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacti',
            new_name='Contacto',
        ),
    ]
