# Generated by Django 4.1.1 on 2022-11-20 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('foto', models.ImageField(blank=True, default='images/usuarios/default.jpg', upload_to='images/usuarios')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('Otro', 'Otro Tipo de Documento')], default='CC', max_length=4, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('fecha_nacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=2, verbose_name='Tipo de Genero')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado'), ('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Empleado', max_length=13, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
