# Generated by Django 4.1.1 on 2022-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='images/usuarios/default.jpg', upload_to='images/usuarios'),
        ),
    ]
