# Generated by Django 4.1.1 on 2022-10-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='presentacion',
        ),
    ]
