# Generated by Django 4.1.1 on 2022-12-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_productos_categoria_remove_productos_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='Categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.marca', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='presentacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.presentacion', verbose_name='Presentación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
