# Generated by Django 4.1.1 on 2022-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_categoria_productos_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='prefijos',
            field=models.CharField(max_length=4, verbose_name='Prefijos'),
        ),
    ]
