# Generated by Django 4.1.1 on 2022-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_presentacion_prefijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('0', 'INACTIVO')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
