# Generated by Django 4.1.1 on 2022-12-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_marca_estado_presentacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('0', 'INACTIVO')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
