# Generated by Django 4.1.1 on 2022-12-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options_alter_proveedor_razonsocial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoComprobante', models.CharField(choices=[('CF', 'Comprobante Factura'), ('NC', 'Nota Crédito')], default='CF', max_length=50, verbose_name='Tipo de Comprobante')),
                ('fechaIngreso', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Ingreso')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
