# Generated by Django 4.1.1 on 2022-12-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
