# Generated by Django 4.1.1 on 2022-12-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'provedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razonSocial',
            field=models.CharField(max_length=50, verbose_name='Razón Social'),
        ),
    ]
